#!/bin/bash
clear
fun_bar () {
comando[0]="$1"
comando[1]="$2"
 (
[[ -e $HOME/fim ]] && rm $HOME/fim
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
 ) > /dev/null 2>&1 &
 tput civis
echo -ne "  \033[1;33mWAIT \033[1;37m- \033[1;33m["
while true; do
   for((i=0; i<18; i++)); do
   echo -ne "\033[1;31m#"
   sleep 0.1s
   done
   [[ -e $HOME/fim ]] && rm $HOME/fim && break
   echo -e "\033[1;33m]"
   sleep 1s
   tput cuu1
   tput dl1
   echo -ne "  \033[1;33mWAIT \033[1;37m- \033[1;33m["
done
echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
tput cnorm
}
echo ""
echo -e "           \033[1;33m● \033[1;32mUPDATE LINUX, It can take time \033[1;33m●\033[0m"
fun_update () {
    apt-get update -y > /dev/null 2>&1 
	apt-get install figlet -y > /dev/null 2>&1
}
fun_bar 'fun_update'
echo ""
clear
#
rm /root/install > /dev/null 2>&1
rm $HOME/install > /dev/null 2>&1
rm /root/PAINEL.zip > /dev/null 2>&1
rm $HOME/PAINEL.zip > /dev/null 2>&1
IP=$(wget -qO- ipv4.icanhazip.com)
echo "Asia/Bangkok" > /etc/timezone
ln -fs /usr/share/zoneinfo/Asia/Bangkok /etc/localtime > /dev/null 2>&1
dpkg-reconfigure --frontend noninteractive tzdata > /dev/null 2>&1
rm $HOME/install > /dev/null 2>&1
rm /root/PAINEL.zip > /dev/null 2>&1
####################################################################################################
echo -e "\E[44;1;37m    INSTALL THE PANEL SSH/DROP/SSL      VIP-VPS     \E[0m"
echo ""
echo -e "                              \033[1;31mBy @cyox.ga\033[1;36m"
echo -e "   VIP-vps" | figlet 
echo -e "                             \033[1;31mPanel-SSH     \033[1;36m"
echo ""
echo -e "\n\033[1;36m  STARTING INSTALLATION \033[1;33m"
echo ""

#
echo -e "           \033[1;33m● \033[1;32mINSTALLING THE APACHE2 \033[1;33m●\033[0m"
fun_apache2 () {
    apt-get install apache2 -y > /dev/null 2>&1
	service apache2 restart > /dev/null 2>&1
}
fun_bar 'fun_apache2'
echo ""
#
echo -e "           \033[1;33m● \033[1;32mINSTALLING MCRYPT \033[1;33m●\033[0m"
fun_mcrypt () {
    apt-get install cron curl unzip -y > /dev/null 2>&1
    apt-get install php5 libapache2-mod-php5 php5-mcrypt -y > /dev/null 2>&1
    service apache2 restart > /dev/null 2>&1
}
fun_bar 'fun_mcrypt'
echo ""
#
echo -e "           \033[1;33m● \033[1;32mINSTALLING THE LIBSSH2 \033[1;33m●\033[0m"
fun_libsh2 () {
apt-get install libssh2-1-dev libssh2-php -y > /dev/null 2>&1
}
fun_bar 'fun_libsh2'

apt-get install php-ssh2 -y > /dev/null 2>&1

if [ "$(php -m |grep ssh2)" = "ssh2" ]; then
  true
else
  clear
  echo -e "\033[1;31m CRITICAL ERROR\033[0m"
  rm $HOME/install > /dev/null 2>&1
  exit
fi
echo ""
#
echo -e "           \033[1;33m● \033[1;32mINSTALLING THE PHP5-CURL \033[1;33m●\033[0m"
fun_curl () {
apt-get install php5-curl > /dev/null 2>&1
service apache2 restart
}
fun_bar 'fun_curl'
echo ""
#
clear
echo -e "\E[44;1;37m    INSTALL THE PAINEL SSH/DROP/SSL      VIP-VPS     \E[0m"
echo ""
echo -e "                              \033[1;31mBy @cyox.ga\033[1;36m"
echo -e "   VIP-vps" | figlet
echo ""
echo -e "\033[1;31m WARNING \033[1;33m!!!"
echo ""
echo -e "\033[1;32mOK\033[1;37m"
sleep 1
fun_bar 'sleep 4'
echo ""
clear
#
echo -e "           \033[1;33m● \033[1;32mFINALIZING INSTALLATION, IT MAY TAKE \033[1;33m● \033[1;33mWAIT...\033[0m"
cd /var/www/html
wget https://raw.githubusercontent.com/Thanatad/ssh-panel-php/main/panel/PAINEL.zip > /dev/null 2>&1
sleep 1
unzip PAINEL.zip > /dev/null 2>&1
rm -rf PAINEL.zip index.html > /dev/null 2>&1
service apache2 restart
sleep 1
cd
service apache2 restart
clear
echo '* * * * * root /usr/bin/php /var/www/html/pages/system/cron.php' >> /etc/crontab
echo '* * * * * root /usr/bin/php /var/www/html/pages/system/cron.ssh.php ' >> /etc/crontab
echo '* * * * * root /usr/bin/php /var/www/html/pages/system/cron.sms.php' >> /etc/crontab
echo '* * * * * root /usr/bin/php /var/www/html/pages/system/cron.online.ssh.php' >> /etc/crontab
echo '10 * * * * root /usr/bin/php /var/www/html/pages/system/cron.servidor.php' >> /etc/crontab
# CLEANING HISTORY USERS ONLINE EVERY 1 MINUTE #
echo '*/1 * * * * root /usr/bin/php /var/www/html/pages/system/cron.limpeza.php' >> /etc/crontab
# BACKUP DATABASE SQL DATABASE EVERY 2 MINUTES #
echo '*/2 * * * * root /bin/autobackup.sh' >> /etc/crontab
/etc/init.d/cron reload > /dev/null 2>&1
/etc/init.d/cron restart > /dev/null 2>&1
cd /bin
rm autobackup.sh > /dev/null 2>&1
wget https://raw.githubusercontent.com/Thanatad/ssh-panel-php/main/panel/autobackup.sh > /dev/null 2>&1 && chmod 777 autobackup.sh && sed -i -e 's/\r$//' autobackup.sh && ./autobackup.sh
# echo '0 */12 * * * root cd /var/www/html/pages/system/ && bash cron.backup.sh && cd /root' >> /etc/crontab
# echo '5 */12 * * * root cd /var/www/html/pages/system/ && /usr/bin/php cron.backup.php && cd /root' >> /etc/crontab
/etc/init.d/cron reload > /dev/null 2>&1
/etc/init.d/cron restart > /dev/null 2>&1
chmod 777 /var/www/html/admin/pages/apis/banco19157
chmod 777 /var/www/html/admin/pages/servidor/ovpn
chmod 777 /var/www/html/admin/pages/download
chmod 777 /var/www/html/admin/pages/faturas/comprovantes
service apache2 restart
sleep 1
service apache2 restart
clear
echo ""
#
clear
IP=$(wget -qO- ipv4.icanhazip.com)
clear
echo -e "   Panel-SSH" | figlet
echo -e "          " | figlet
echo -e "                 \033[1;31mBy @cyox.ga\033[1;36m"
echo ""
echo -e "\033[1;36m YOUR PANEL:\033[1;37m http://$IP/\033[0m"
echo -e "\033[1;36m USER:\033[1;37m admin\033[0m"
echo -e "\033[1;36m PASSWORD:\033[1;37m admin\033[0m"
echo ""
echo -e "\033[1;33m Change password when logging into the panel>> Settings>> old password: admin >> New password: \033[0m"
sed -i "s;upload_max_filesize = 2M;upload_max_filesize = 20M;g" /etc/php5/apache2/php.ini > /dev/null 2>&1
service apache2 restart
echo ""
echo -e "\033[1;31m VPS WILL RESTART IN 10 SECONDS...\033[0m"
sleep 15
echo -e "\033[1;31mREBOOT...\033[0m"
shutdown -r now
cat /dev/null > ~/.bash_history && history -c
rm /root/install > /dev/null 2>&1
rm /root/PAINEL.zip > /dev/null 2>&1
